spring:
  config:
    import:
      - classpath:gpt-script.yml
      - classpath:openai.properties
      - classpath:application-db.yml
      - classpath:application-mail.properties

  output:
    ansi:
      enabled: always
